// AUTO-GENERATED by scripts/optimize-media.mjs — do not edit by hand.
// Re-run `npm run optimize:media` after adding or replacing any image, logo or video.
import type { MediaManifest } from './media.types';

export const MEDIA_MANIFEST: MediaManifest = {
  "images": {
    "assets/img/assessment/fat-beehive/fat-beehive1.jpeg": {
      "width": 3456,
      "height": 1994,
      "avif": "/assets/media/img/fat-beehive1-640.b3579925b4.avif 640w, /assets/media/img/fat-beehive1-1280.5f71bff9ff.avif 1280w, /assets/media/img/fat-beehive1-1920.46ff5e3e18.avif 1920w",
      "webp": "/assets/media/img/fat-beehive1-640.478506e761.webp 640w, /assets/media/img/fat-beehive1-1280.9f6df72b8b.webp 1280w, /assets/media/img/fat-beehive1-1920.0bb1cb4fbd.webp 1920w",
      "fallback": "/assets/media/img/fat-beehive1-1280.845b2a2144.jpg",
      "source": "82bd0a05ab|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/assessment/logic-bank/logic1.jpeg": {
      "width": 1280,
      "height": 740,
      "avif": "/assets/media/img/logic1-640.88871cff22.avif 640w, /assets/media/img/logic1-1280.b24e16deb0.avif 1280w",
      "webp": "/assets/media/img/logic1-640.ff17c3a2ab.webp 640w, /assets/media/img/logic1-1280.0f9b434a55.webp 1280w",
      "fallback": "/assets/media/img/logic1-1280.7f43f4552e.jpg",
      "source": "de7382d10a|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/assessment/logic-bank/logic2.jpeg": {
      "width": 3456,
      "height": 1996,
      "avif": "/assets/media/img/logic2-640.c03a3e1b56.avif 640w, /assets/media/img/logic2-1280.c8a6976a31.avif 1280w, /assets/media/img/logic2-1920.d1363534d2.avif 1920w",
      "webp": "/assets/media/img/logic2-640.efef5abed7.webp 640w, /assets/media/img/logic2-1280.6d8a3ea697.webp 1280w, /assets/media/img/logic2-1920.f27ebd3656.webp 1920w",
      "fallback": "/assets/media/img/logic2-1280.7cafbd8f61.jpg",
      "source": "0c0d26f4fa|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/assessment/logic-bank/logic3.jpeg": {
      "width": 3456,
      "height": 1996,
      "avif": "/assets/media/img/logic3-640.a5056a6b83.avif 640w, /assets/media/img/logic3-1280.52d99cfb3f.avif 1280w, /assets/media/img/logic3-1920.c54feb7729.avif 1920w",
      "webp": "/assets/media/img/logic3-640.468716248a.webp 640w, /assets/media/img/logic3-1280.d38b2cf133.webp 1280w, /assets/media/img/logic3-1920.d856832918.webp 1920w",
      "fallback": "/assets/media/img/logic3-1280.8c041e79d9.jpg",
      "source": "9484f47d6d|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/assessment/logic-bank/logic4.jpeg": {
      "width": 3456,
      "height": 1996,
      "avif": "/assets/media/img/logic4-640.b0495cf322.avif 640w, /assets/media/img/logic4-1280.6ae45d3297.avif 1280w, /assets/media/img/logic4-1920.0bf53b453a.avif 1920w",
      "webp": "/assets/media/img/logic4-640.4a6378ff53.webp 640w, /assets/media/img/logic4-1280.53fdeb304a.webp 1280w, /assets/media/img/logic4-1920.cc12df8774.webp 1920w",
      "fallback": "/assets/media/img/logic4-1280.c3526643be.jpg",
      "source": "dfe3f188c8|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/assessment/logic-bank/logic5.jpeg": {
      "width": 3456,
      "height": 2000,
      "avif": "/assets/media/img/logic5-640.ea4ea98f1f.avif 640w, /assets/media/img/logic5-1280.eb2ce45fc4.avif 1280w, /assets/media/img/logic5-1920.95764dc6b6.avif 1920w",
      "webp": "/assets/media/img/logic5-640.d09bfaeb23.webp 640w, /assets/media/img/logic5-1280.43e23db0c5.webp 1280w, /assets/media/img/logic5-1920.651827af29.webp 1920w",
      "fallback": "/assets/media/img/logic5-1280.8e3a7bd2cc.jpg",
      "source": "e1b5dfd38b|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/assessment/naologic/naologic1.jpeg": {
      "width": 3456,
      "height": 1998,
      "avif": "/assets/media/img/naologic1-640.9b88d642a3.avif 640w, /assets/media/img/naologic1-1280.f2e37694a4.avif 1280w, /assets/media/img/naologic1-1920.fde88e5ed7.avif 1920w",
      "webp": "/assets/media/img/naologic1-640.5a45426e4a.webp 640w, /assets/media/img/naologic1-1280.a19a2ee995.webp 1280w, /assets/media/img/naologic1-1920.ba8633b724.webp 1920w",
      "fallback": "/assets/media/img/naologic1-1280.37d366c25d.jpg",
      "source": "114d18c0f0|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/assessment/naologic/naologic2.jpeg": {
      "width": 3456,
      "height": 1994,
      "avif": "/assets/media/img/naologic2-640.80f4f3f8b0.avif 640w, /assets/media/img/naologic2-1280.3fabb5b34b.avif 1280w, /assets/media/img/naologic2-1920.cf70dfb3a3.avif 1920w",
      "webp": "/assets/media/img/naologic2-640.fb7a09eecc.webp 640w, /assets/media/img/naologic2-1280.28824a7d78.webp 1280w, /assets/media/img/naologic2-1920.92e70ce2a7.webp 1920w",
      "fallback": "/assets/media/img/naologic2-1280.0e0275be36.jpg",
      "source": "5aa0a77be9|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/cap-dashboard.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/cap-dashboard-640.0e23f7344b.avif 640w, /assets/media/img/cap-dashboard-1280.02af562fe1.avif 1280w, /assets/media/img/cap-dashboard-1920.e871f3e8d5.avif 1920w",
      "webp": "/assets/media/img/cap-dashboard-640.91093da824.webp 640w, /assets/media/img/cap-dashboard-1280.621e628542.webp 1280w, /assets/media/img/cap-dashboard-1920.451869081f.webp 1920w",
      "fallback": "/assets/media/img/cap-dashboard-1280.c7ae59cdf8.jpg",
      "source": "b41af02065|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/cap-disbursements.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/cap-disbursements-640.13b850e717.avif 640w, /assets/media/img/cap-disbursements-1280.049fdb1afb.avif 1280w, /assets/media/img/cap-disbursements-1920.7e4bc5b839.avif 1920w",
      "webp": "/assets/media/img/cap-disbursements-640.9dece8a019.webp 640w, /assets/media/img/cap-disbursements-1280.d5ce18ed13.webp 1280w, /assets/media/img/cap-disbursements-1920.def561a8e6.webp 1920w",
      "fallback": "/assets/media/img/cap-disbursements-1280.d1d5415397.jpg",
      "source": "42b252490c|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/cap-facility-requests.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/cap-facility-requests-640.b1ffa5a390.avif 640w, /assets/media/img/cap-facility-requests-1280.296b049b18.avif 1280w, /assets/media/img/cap-facility-requests-1920.21cb835bd3.avif 1920w",
      "webp": "/assets/media/img/cap-facility-requests-640.cbb267f462.webp 640w, /assets/media/img/cap-facility-requests-1280.4065fa4453.webp 1280w, /assets/media/img/cap-facility-requests-1920.c1e1c58cdc.webp 1920w",
      "fallback": "/assets/media/img/cap-facility-requests-1280.fd59c4c77a.jpg",
      "source": "a15029d8c1|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/cap-login.jpeg": {
      "width": 3422,
      "height": 1994,
      "avif": "/assets/media/img/cap-login-640.73864ccaf3.avif 640w, /assets/media/img/cap-login-1280.3b74ddb170.avif 1280w, /assets/media/img/cap-login-1920.7279dee764.avif 1920w",
      "webp": "/assets/media/img/cap-login-640.f386393415.webp 640w, /assets/media/img/cap-login-1280.194d3251b4.webp 1280w, /assets/media/img/cap-login-1920.48455ddedd.webp 1920w",
      "fallback": "/assets/media/img/cap-login-1280.49563b389a.jpg",
      "source": "0731edb239|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/costaff-assistant.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/costaff-assistant-640.64461f2d08.avif 640w, /assets/media/img/costaff-assistant-1280.d087049530.avif 1280w, /assets/media/img/costaff-assistant-1920.d01940dc63.avif 1920w",
      "webp": "/assets/media/img/costaff-assistant-640.9ac31d9147.webp 640w, /assets/media/img/costaff-assistant-1280.b2fa014160.webp 1280w, /assets/media/img/costaff-assistant-1920.97cece5abf.webp 1920w",
      "fallback": "/assets/media/img/costaff-assistant-1280.96bf280eac.jpg",
      "source": "6bc5f42270|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/costaff-calendar.avif": {
      "width": 1884,
      "height": 1176,
      "avif": "/assets/media/img/costaff-calendar-640.695c50a502.avif 640w, /assets/media/img/costaff-calendar-1280.0318717883.avif 1280w, /assets/media/img/costaff-calendar-1884.09f272ab85.avif 1884w",
      "webp": "/assets/media/img/costaff-calendar-640.203823a4da.webp 640w, /assets/media/img/costaff-calendar-1280.821f3b85b5.webp 1280w, /assets/media/img/costaff-calendar-1884.c4f4104382.webp 1884w",
      "fallback": "/assets/media/img/costaff-calendar-1280.996e21ef8c.jpg",
      "source": "0c03d1c3ae|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/costaff-home.jpeg": {
      "width": 1280,
      "height": 741,
      "avif": "/assets/media/img/costaff-home-640.41c4a9b409.avif 640w, /assets/media/img/costaff-home-1280.554c73c31e.avif 1280w",
      "webp": "/assets/media/img/costaff-home-640.77c8f1be36.webp 640w, /assets/media/img/costaff-home-1280.0ace1182d0.webp 1280w",
      "fallback": "/assets/media/img/costaff-home-1280.a142712496.jpg",
      "source": "c8d8ce028b|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/costaff-inbox.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/costaff-inbox-640.515ebcac34.avif 640w, /assets/media/img/costaff-inbox-1280.cd9e17b3e0.avif 1280w, /assets/media/img/costaff-inbox-1920.19825da1c8.avif 1920w",
      "webp": "/assets/media/img/costaff-inbox-640.1238add0d5.webp 640w, /assets/media/img/costaff-inbox-1280.855ee829a9.webp 1280w, /assets/media/img/costaff-inbox-1920.2c076fef80.webp 1920w",
      "fallback": "/assets/media/img/costaff-inbox-1280.918e48ce5c.jpg",
      "source": "b6c3d7d248|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/costaff-week.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/costaff-week-640.8075f3e8a2.avif 640w, /assets/media/img/costaff-week-1280.45280c21c5.avif 1280w, /assets/media/img/costaff-week-1920.41cad9c032.avif 1920w",
      "webp": "/assets/media/img/costaff-week-640.bca6c26abb.webp 640w, /assets/media/img/costaff-week-1280.e0b6c0968d.webp 1280w, /assets/media/img/costaff-week-1920.35a858310d.webp 1920w",
      "fallback": "/assets/media/img/costaff-week-1280.7f2f4dd8a8.jpg",
      "source": "9f0139770b|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/award-cheerleader.png": {
      "width": 265,
      "height": 297,
      "avif": "/assets/media/img/award-cheerleader-265.014f6ae1c7.avif 265w",
      "webp": "/assets/media/img/award-cheerleader-265.0726c05a1b.webp 265w",
      "fallback": "/assets/media/img/award-cheerleader-265.634ccab26b.png",
      "source": "2ea6e45c05|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/award-early-riser.png": {
      "width": 273,
      "height": 298,
      "avif": "/assets/media/img/award-early-riser-273.feb6cf160b.avif 273w",
      "webp": "/assets/media/img/award-early-riser-273.82b93f213d.webp 273w",
      "fallback": "/assets/media/img/award-early-riser-273.d01a2f9ba1.png",
      "source": "f0d54eeae2|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/award-flawless-finisher.png": {
      "width": 254,
      "height": 297,
      "avif": "/assets/media/img/award-flawless-finisher-254.8e5e2132df.avif 254w",
      "webp": "/assets/media/img/award-flawless-finisher-254.fe9428d063.webp 254w",
      "fallback": "/assets/media/img/award-flawless-finisher-254.184eedcd67.png",
      "source": "41d94e9698|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/award-league-mvp.png": {
      "width": 267,
      "height": 272,
      "avif": "/assets/media/img/award-league-mvp-267.74ba6cbf06.avif 267w",
      "webp": "/assets/media/img/award-league-mvp-267.51e91c4be0.webp 267w",
      "fallback": "/assets/media/img/award-league-mvp-267.5455418111.png",
      "source": "6a32e56637|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/award-legend.png": {
      "width": 274,
      "height": 297,
      "avif": "/assets/media/img/award-legend-274.2c36247e32.avif 274w",
      "webp": "/assets/media/img/award-legend-274.f229f57d24.webp 274w",
      "fallback": "/assets/media/img/award-legend-274.31d10634bb.png",
      "source": "0341525f46|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/award-mistake-mechanic.png": {
      "width": 274,
      "height": 296,
      "avif": "/assets/media/img/award-mistake-mechanic-274.6000f85495.avif 274w",
      "webp": "/assets/media/img/award-mistake-mechanic-274.0401a86499.webp 274w",
      "fallback": "/assets/media/img/award-mistake-mechanic-274.07a10bb70c.png",
      "source": "15c3d7f27a|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/award-perfect-week.png": {
      "width": 274,
      "height": 298,
      "avif": "/assets/media/img/award-perfect-week-274.7bfff9da0d.avif 274w",
      "webp": "/assets/media/img/award-perfect-week-274.8a31f584cb.webp 274w",
      "fallback": "/assets/media/img/award-perfect-week-274.ac7aa8e798.png",
      "source": "b53e459e79|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/award-quest-explorer.png": {
      "width": 274,
      "height": 297,
      "avif": "/assets/media/img/award-quest-explorer-274.6ea72c8317.avif 274w",
      "webp": "/assets/media/img/award-quest-explorer-274.e376dd78be.webp 274w",
      "fallback": "/assets/media/img/award-quest-explorer-274.c42b59b109.png",
      "source": "7e1a20ecbe|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/award-sleepwalker.png": {
      "width": 254,
      "height": 296,
      "avif": "/assets/media/img/award-sleepwalker-254.e668cf21bd.avif 254w",
      "webp": "/assets/media/img/award-sleepwalker-254.6644b470bf.webp 254w",
      "fallback": "/assets/media/img/award-sleepwalker-254.2db464bbbc.png",
      "source": "3166af1c24|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/award-social-butterfly.png": {
      "width": 239,
      "height": 251,
      "avif": "/assets/media/img/award-social-butterfly-239.222bc9ac38.avif 239w",
      "webp": "/assets/media/img/award-social-butterfly-239.6632dc7681.webp 239w",
      "fallback": "/assets/media/img/award-social-butterfly-239.fb8ec37029.png",
      "source": "35446c3f1b|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/award-speed-racer.png": {
      "width": 254,
      "height": 296,
      "avif": "/assets/media/img/award-speed-racer-254.7699fff6e8.avif 254w",
      "webp": "/assets/media/img/award-speed-racer-254.5e9cd6c4bd.webp 254w",
      "fallback": "/assets/media/img/award-speed-racer-254.7acb9f1334.png",
      "source": "d4da6f50fc|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/award-xp-olympian.png": {
      "width": 254,
      "height": 296,
      "avif": "/assets/media/img/award-xp-olympian-254.5b9d2adecb.avif 254w",
      "webp": "/assets/media/img/award-xp-olympian-254.8a66e926a5.webp 254w",
      "fallback": "/assets/media/img/award-xp-olympian-254.1dafd895c8.png",
      "source": "603fb29793|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/month-apr.png": {
      "width": 220,
      "height": 228,
      "avif": "/assets/media/img/month-apr-220.12b6775a3b.avif 220w",
      "webp": "/assets/media/img/month-apr-220.234ebc2fa4.webp 220w",
      "fallback": "/assets/media/img/month-apr-220.70de695b10.png",
      "source": "da95636222|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/month-aug.png": {
      "width": 207,
      "height": 231,
      "avif": "/assets/media/img/month-aug-207.bf7c25eb77.avif 207w",
      "webp": "/assets/media/img/month-aug-207.ea4b190898.webp 207w",
      "fallback": "/assets/media/img/month-aug-207.cff02706a5.png",
      "source": "af565119fe|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/month-jul.png": {
      "width": 207,
      "height": 242,
      "avif": "/assets/media/img/month-jul-207.a6a69b5f74.avif 207w",
      "webp": "/assets/media/img/month-jul-207.ccc2d36c82.webp 207w",
      "fallback": "/assets/media/img/month-jul-207.557b82e30a.png",
      "source": "56dc9a2eee|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/month-jun.png": {
      "width": 205,
      "height": 226,
      "avif": "/assets/media/img/month-jun-205.3881debe7e.avif 205w",
      "webp": "/assets/media/img/month-jun-205.4c802938b8.webp 205w",
      "fallback": "/assets/media/img/month-jun-205.b145b53a6b.png",
      "source": "c4d0946787|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/month-mar.png": {
      "width": 216,
      "height": 233,
      "avif": "/assets/media/img/month-mar-216.35adab4724.avif 216w",
      "webp": "/assets/media/img/month-mar-216.a66b56ec7e.webp 216w",
      "fallback": "/assets/media/img/month-mar-216.3c3ce107cb.png",
      "source": "22f6986884|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/month-may.png": {
      "width": 204,
      "height": 225,
      "avif": "/assets/media/img/month-may-204.0d4f484ee5.avif 204w",
      "webp": "/assets/media/img/month-may-204.cfbe0b3661.webp 204w",
      "fallback": "/assets/media/img/month-may-204.b9ce8a5bc6.png",
      "source": "de015cc28b|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/month-oct.png": {
      "width": 226,
      "height": 234,
      "avif": "/assets/media/img/month-oct-226.d6999ef430.avif 226w",
      "webp": "/assets/media/img/month-oct-226.fdd0c23c78.webp 226w",
      "fallback": "/assets/media/img/month-oct-226.863e780c3f.png",
      "source": "688fce26cb|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/month-sep.png": {
      "width": 234,
      "height": 246,
      "avif": "/assets/media/img/month-sep-234.6acd222675.avif 234w",
      "webp": "/assets/media/img/month-sep-234.7800155059.webp 234w",
      "fallback": "/assets/media/img/month-sep-234.b9f4c7992c.png",
      "source": "f63efab756|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/record-league.png": {
      "width": 221,
      "height": 258,
      "avif": "/assets/media/img/record-league-221.5899fe3197.avif 221w",
      "webp": "/assets/media/img/record-league-221.27eb500717.webp 221w",
      "fallback": "/assets/media/img/record-league-221.91ee036d59.png",
      "source": "31488c070c|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/record-most-xp.png": {
      "width": 234,
      "height": 258,
      "avif": "/assets/media/img/record-most-xp-234.dad9693598.avif 234w",
      "webp": "/assets/media/img/record-most-xp-234.2ca79c83af.webp 234w",
      "fallback": "/assets/media/img/record-most-xp-234.4004fb5e05.png",
      "source": "c803397edc|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/record-perfect-lessons.png": {
      "width": 220,
      "height": 246,
      "avif": "/assets/media/img/record-perfect-lessons-220.6ed3771756.avif 220w",
      "webp": "/assets/media/img/record-perfect-lessons-220.0236c39d0d.webp 220w",
      "fallback": "/assets/media/img/record-perfect-lessons-220.6a07c3e919.png",
      "source": "dbb128cdb0|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/duolingo/record-streak.png": {
      "width": 201,
      "height": 258,
      "avif": "/assets/media/img/record-streak-201.c8f836ce4e.avif 201w",
      "webp": "/assets/media/img/record-streak-201.35e815cae9.webp 201w",
      "fallback": "/assets/media/img/record-streak-201.9be28f6fa5.png",
      "source": "2dacbe6665|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/fraud-dashboard-dark.png": {
      "width": 1830,
      "height": 900,
      "avif": "/assets/media/img/fraud-dashboard-dark-640.04b880f818.avif 640w, /assets/media/img/fraud-dashboard-dark-1280.a73593fb76.avif 1280w, /assets/media/img/fraud-dashboard-dark-1830.5cf7b6250c.avif 1830w",
      "webp": "/assets/media/img/fraud-dashboard-dark-640.c5c6788278.webp 640w, /assets/media/img/fraud-dashboard-dark-1280.99add2562a.webp 1280w, /assets/media/img/fraud-dashboard-dark-1830.6c0e490d59.webp 1830w",
      "fallback": "/assets/media/img/fraud-dashboard-dark-1280.4897830675.jpg",
      "source": "a132349412|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/fraud-details-dark.png": {
      "width": 1118,
      "height": 762,
      "avif": "/assets/media/img/fraud-details-dark-640.a3e99dba3b.avif 640w, /assets/media/img/fraud-details-dark-1118.5982da4358.avif 1118w",
      "webp": "/assets/media/img/fraud-details-dark-640.1b570831fa.webp 640w, /assets/media/img/fraud-details-dark-1118.9112235db6.webp 1118w",
      "fallback": "/assets/media/img/fraud-details-dark-1118.78e08be10a.jpg",
      "source": "bc1df2d12e|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/fraud-flagged-transactions.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/fraud-flagged-transactions-640.31643f9a3e.avif 640w, /assets/media/img/fraud-flagged-transactions-1280.78071fba0d.avif 1280w, /assets/media/img/fraud-flagged-transactions-1920.8ca5b2ad23.avif 1920w",
      "webp": "/assets/media/img/fraud-flagged-transactions-640.abae72cbec.webp 640w, /assets/media/img/fraud-flagged-transactions-1280.fff7a3046d.webp 1280w, /assets/media/img/fraud-flagged-transactions-1920.13adea7dbb.webp 1920w",
      "fallback": "/assets/media/img/fraud-flagged-transactions-1280.92ff139e26.jpg",
      "source": "8188d231c2|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/fraud-live-dashboard.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/fraud-live-dashboard-640.4c7f2d4bb4.avif 640w, /assets/media/img/fraud-live-dashboard-1280.ee0e1c9191.avif 1280w, /assets/media/img/fraud-live-dashboard-1920.48f050d9dc.avif 1920w",
      "webp": "/assets/media/img/fraud-live-dashboard-640.378b90a61e.webp 640w, /assets/media/img/fraud-live-dashboard-1280.f1c2601265.webp 1280w, /assets/media/img/fraud-live-dashboard-1920.3bdecb80f2.webp 1920w",
      "fallback": "/assets/media/img/fraud-live-dashboard-1280.5cdc65cbbe.jpg",
      "source": "762ad45d33|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/fraud-rule-engines.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/fraud-rule-engines-640.029171dc45.avif 640w, /assets/media/img/fraud-rule-engines-1280.e8a566726f.avif 1280w, /assets/media/img/fraud-rule-engines-1920.6156e7fd25.avif 1920w",
      "webp": "/assets/media/img/fraud-rule-engines-640.ee80650ad3.webp 640w, /assets/media/img/fraud-rule-engines-1280.c759fa1f4c.webp 1280w, /assets/media/img/fraud-rule-engines-1920.b528e48333.webp 1920w",
      "fallback": "/assets/media/img/fraud-rule-engines-1280.80aafe2d72.jpg",
      "source": "f4b6ad053b|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/gta-details.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/gta-details-640.329d82e84c.avif 640w, /assets/media/img/gta-details-1280.53e30b6bbf.avif 1280w, /assets/media/img/gta-details-1920.fbaf392eed.avif 1920w",
      "webp": "/assets/media/img/gta-details-640.09ec27b02d.webp 640w, /assets/media/img/gta-details-1280.a988cb0014.webp 1280w, /assets/media/img/gta-details-1920.33ffeac2d3.webp 1920w",
      "fallback": "/assets/media/img/gta-details-1280.2c0770c9b4.jpg",
      "source": "d109e8c51f|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/gta-documents.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/gta-documents-640.f3e1e1b6c9.avif 640w, /assets/media/img/gta-documents-1280.6803dd3b67.avif 1280w, /assets/media/img/gta-documents-1920.44d694b20d.avif 1920w",
      "webp": "/assets/media/img/gta-documents-640.e6a8ee3df4.webp 640w, /assets/media/img/gta-documents-1280.89bc3022bb.webp 1280w, /assets/media/img/gta-documents-1920.d96e5aa7f7.webp 1920w",
      "fallback": "/assets/media/img/gta-documents-1280.6e40a8a25c.jpg",
      "source": "7e2a8a6561|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/gta-home.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/gta-home-640.918d9e4b42.avif 640w, /assets/media/img/gta-home-1280.fbee7f26bd.avif 1280w, /assets/media/img/gta-home-1920.8a6a0ca597.avif 1920w",
      "webp": "/assets/media/img/gta-home-640.1e8593c481.webp 640w, /assets/media/img/gta-home-1280.06feffc8dc.webp 1280w, /assets/media/img/gta-home-1920.7b4bb26111.webp 1920w",
      "fallback": "/assets/media/img/gta-home-1280.e3c7c8d5f7.jpg",
      "source": "c71ae0a6e8|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/gta-import.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/gta-import-640.cac693c20b.avif 640w, /assets/media/img/gta-import-1280.95553060ae.avif 1280w, /assets/media/img/gta-import-1920.3395ca6437.avif 1920w",
      "webp": "/assets/media/img/gta-import-640.d484cd562f.webp 640w, /assets/media/img/gta-import-1280.5df25d58c1.webp 1280w, /assets/media/img/gta-import-1920.924fe79fa9.webp 1920w",
      "fallback": "/assets/media/img/gta-import-1280.309a7d2089.jpg",
      "source": "f5d7589135|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/gta-settings.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/gta-settings-640.f96843c80f.avif 640w, /assets/media/img/gta-settings-1280.5bf6985d2e.avif 1280w, /assets/media/img/gta-settings-1920.f64bf97f24.avif 1920w",
      "webp": "/assets/media/img/gta-settings-640.45f8451357.webp 640w, /assets/media/img/gta-settings-1280.e2b007171e.webp 1280w, /assets/media/img/gta-settings-1920.8ebe1e6a4c.webp 1920w",
      "fallback": "/assets/media/img/gta-settings-1280.1d5d17a0dc.jpg",
      "source": "4e23bf9584|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/nxp-applications.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/nxp-applications-640.9fb61f2a69.avif 640w, /assets/media/img/nxp-applications-1280.d830e21594.avif 1280w, /assets/media/img/nxp-applications-1920.7ba9a30fa4.avif 1920w",
      "webp": "/assets/media/img/nxp-applications-640.5fdd805b3f.webp 640w, /assets/media/img/nxp-applications-1280.3ca2c6214e.webp 1280w, /assets/media/img/nxp-applications-1920.f68753a75b.webp 1920w",
      "fallback": "/assets/media/img/nxp-applications-1280.a2bdde860e.jpg",
      "source": "aa779c0b05|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/nxp-cancelation.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/nxp-cancelation-640.fa6ca00706.avif 640w, /assets/media/img/nxp-cancelation-1280.014d6d3f97.avif 1280w, /assets/media/img/nxp-cancelation-1920.7f9101d76b.avif 1920w",
      "webp": "/assets/media/img/nxp-cancelation-640.194a3d2c54.webp 640w, /assets/media/img/nxp-cancelation-1280.c5779357bc.webp 1280w, /assets/media/img/nxp-cancelation-1920.fd8d40c33b.webp 1920w",
      "fallback": "/assets/media/img/nxp-cancelation-1280.d9d999d869.jpg",
      "source": "4e38fb45ad|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/nxp-ness.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/nxp-ness-640.3ad5b1808e.avif 640w, /assets/media/img/nxp-ness-1280.9724c1d721.avif 1280w, /assets/media/img/nxp-ness-1920.14efdc3bbf.avif 1920w",
      "webp": "/assets/media/img/nxp-ness-640.323f86c4a0.webp 640w, /assets/media/img/nxp-ness-1280.eb87a8eb87.webp 1280w, /assets/media/img/nxp-ness-1920.9ffa0c040d.webp 1920w",
      "fallback": "/assets/media/img/nxp-ness-1280.ef12f37038.jpg",
      "source": "f23c0aeee0|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/nxp-overview.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/nxp-overview-640.ce9318fe8e.avif 640w, /assets/media/img/nxp-overview-1280.87c076674d.avif 1280w, /assets/media/img/nxp-overview-1920.c5301de9f5.avif 1920w",
      "webp": "/assets/media/img/nxp-overview-640.c043d212f9.webp 640w, /assets/media/img/nxp-overview-1280.efad304173.webp 1280w, /assets/media/img/nxp-overview-1920.d356653371.webp 1920w",
      "fallback": "/assets/media/img/nxp-overview-1280.8b66e035b4.jpg",
      "source": "9a7d55d0ff|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/nxp-repatriation.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/nxp-repatriation-640.105fc80543.avif 640w, /assets/media/img/nxp-repatriation-1280.fbe2612099.avif 1280w, /assets/media/img/nxp-repatriation-1920.7d774e2450.avif 1920w",
      "webp": "/assets/media/img/nxp-repatriation-640.d9537c325f.webp 640w, /assets/media/img/nxp-repatriation-1280.7808b9d3ba.webp 1280w, /assets/media/img/nxp-repatriation-1920.9b1b41dc43.webp 1920w",
      "fallback": "/assets/media/img/nxp-repatriation-1280.b2af308787.jpg",
      "source": "d64cd01aa4|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/tiger-naps-direct.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/tiger-naps-direct-640.2928f3fdb0.avif 640w, /assets/media/img/tiger-naps-direct-1280.4b5028f00d.avif 1280w, /assets/media/img/tiger-naps-direct-1920.8967eb3160.avif 1920w",
      "webp": "/assets/media/img/tiger-naps-direct-640.448f42708c.webp 640w, /assets/media/img/tiger-naps-direct-1280.4acb212de6.webp 1280w, /assets/media/img/tiger-naps-direct-1920.e177cd723a.webp 1920w",
      "fallback": "/assets/media/img/tiger-naps-direct-1280.421145b2df.jpg",
      "source": "5b56fa5778|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/tiger-nip-dashboard.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/tiger-nip-dashboard-640.f1515af539.avif 640w, /assets/media/img/tiger-nip-dashboard-1280.044c20fcf8.avif 1280w, /assets/media/img/tiger-nip-dashboard-1920.38747a17ca.avif 1920w",
      "webp": "/assets/media/img/tiger-nip-dashboard-640.eb6eae6a66.webp 640w, /assets/media/img/tiger-nip-dashboard-1280.33f45dc422.webp 1280w, /assets/media/img/tiger-nip-dashboard-1920.b5b289fad4.webp 1920w",
      "fallback": "/assets/media/img/tiger-nip-dashboard-1280.15a78073b5.jpg",
      "source": "ae1b1fe57c|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/tiger-queue.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/tiger-queue-640.95402dc679.avif 640w, /assets/media/img/tiger-queue-1280.41a726fb9d.avif 1280w, /assets/media/img/tiger-queue-1920.14271bac55.avif 1920w",
      "webp": "/assets/media/img/tiger-queue-640.5dfb847b4c.webp 640w, /assets/media/img/tiger-queue-1280.bcfb524d0b.webp 1280w, /assets/media/img/tiger-queue-1920.f68d4a4968.webp 1920w",
      "fallback": "/assets/media/img/tiger-queue-1280.b3c7a7794e.jpg",
      "source": "a46110b1ef|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/tiger-search.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/tiger-search-640.f523f9df12.avif 640w, /assets/media/img/tiger-search-1280.8e15a2dbc2.avif 1280w, /assets/media/img/tiger-search-1920.c5b1ed2090.avif 1920w",
      "webp": "/assets/media/img/tiger-search-640.e615ac08a6.webp 640w, /assets/media/img/tiger-search-1280.55e3f986a9.webp 1280w, /assets/media/img/tiger-search-1920.a2cacd475a.webp 1920w",
      "fallback": "/assets/media/img/tiger-search-1280.31350c47ac.jpg",
      "source": "3e749d5590|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/tiger-teller.png": {
      "width": 2956,
      "height": 1663,
      "avif": "/assets/media/img/tiger-teller-640.6715d2f838.avif 640w, /assets/media/img/tiger-teller-1280.f2cf735847.avif 1280w, /assets/media/img/tiger-teller-1920.e27e904e23.avif 1920w",
      "webp": "/assets/media/img/tiger-teller-640.214ddab5b6.webp 640w, /assets/media/img/tiger-teller-1280.fb1ea36799.webp 1280w, /assets/media/img/tiger-teller-1920.6b7ffef446.webp 1920w",
      "fallback": "/assets/media/img/tiger-teller-1280.3656e88ed3.jpg",
      "source": "8d6d443d8a|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/xpath-dashboard.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/xpath-dashboard-640.f79dd4e4fe.avif 640w, /assets/media/img/xpath-dashboard-1280.6717a73c9c.avif 1280w, /assets/media/img/xpath-dashboard-1920.6bd1b64229.avif 1920w",
      "webp": "/assets/media/img/xpath-dashboard-640.0f6230026e.webp 640w, /assets/media/img/xpath-dashboard-1280.a461112037.webp 1280w, /assets/media/img/xpath-dashboard-1920.0d2b2e82f0.webp 1920w",
      "fallback": "/assets/media/img/xpath-dashboard-1280.37334b4467.jpg",
      "source": "fb77f59238|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/xpath-deposits.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/xpath-deposits-640.abbe6b277f.avif 640w, /assets/media/img/xpath-deposits-1280.0a983e72d5.avif 1280w, /assets/media/img/xpath-deposits-1920.5ecc86c765.avif 1920w",
      "webp": "/assets/media/img/xpath-deposits-640.e5d596f9d9.webp 640w, /assets/media/img/xpath-deposits-1280.c93228e260.webp 1280w, /assets/media/img/xpath-deposits-1920.2045b2b5d0.webp 1920w",
      "fallback": "/assets/media/img/xpath-deposits-1280.932bec8251.jpg",
      "source": "66868d2806|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/xpath-merchants.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/xpath-merchants-640.4b1b058591.avif 640w, /assets/media/img/xpath-merchants-1280.17499536a4.avif 1280w, /assets/media/img/xpath-merchants-1920.4933867650.avif 1920w",
      "webp": "/assets/media/img/xpath-merchants-640.0cd9112b42.webp 640w, /assets/media/img/xpath-merchants-1280.e7456d384e.webp 1280w, /assets/media/img/xpath-merchants-1920.ef6c2b2f53.webp 1920w",
      "fallback": "/assets/media/img/xpath-merchants-1280.a8ba9dec53.jpg",
      "source": "9c27a4b454|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/xpath-payments-memo.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/xpath-payments-memo-640.f9204c8186.avif 640w, /assets/media/img/xpath-payments-memo-1280.f8d3315548.avif 1280w, /assets/media/img/xpath-payments-memo-1920.39b8c17040.avif 1920w",
      "webp": "/assets/media/img/xpath-payments-memo-640.735f462026.webp 640w, /assets/media/img/xpath-payments-memo-1280.6eb09bd003.webp 1280w, /assets/media/img/xpath-payments-memo-1920.d959e224c1.webp 1920w",
      "fallback": "/assets/media/img/xpath-payments-memo-1280.96a8ee7c1d.jpg",
      "source": "6bfda7ea7e|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/xpath-payments.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/xpath-payments-640.5a2881c344.avif 640w, /assets/media/img/xpath-payments-1280.3f965edeb9.avif 1280w, /assets/media/img/xpath-payments-1920.7a64e296ec.avif 1920w",
      "webp": "/assets/media/img/xpath-payments-640.bf3402fa7e.webp 640w, /assets/media/img/xpath-payments-1280.910af7347b.webp 1280w, /assets/media/img/xpath-payments-1920.161f4d906b.webp 1920w",
      "fallback": "/assets/media/img/xpath-payments-1280.fea4dbe85d.jpg",
      "source": "8660bd8a46|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    }
  },
  "logos": {
    "assets/logos/conclase.svg": {
      "src": "/assets/media/logos/conclase.144f6b1674.webp",
      "width": 334,
      "height": 144,
      "source": "cbc0c8af82|v1|webp q90 a100 h144"
    },
    "assets/logos/golden-scepter.svg": {
      "src": "/assets/media/logos/golden-scepter.a9dd805dc0.webp",
      "width": 365,
      "height": 144,
      "source": "3be337cffc|v1|webp q90 a100 h144"
    },
    "assets/logos/jumbo.svg": {
      "src": "/assets/media/logos/jumbo.ad1eb4180d.webp",
      "width": 144,
      "height": 144,
      "source": "3f735e57db|v1|webp q90 a100 h144"
    },
    "assets/logos/upperlink.svg": {
      "src": "/assets/media/logos/upperlink.983586f278.webp",
      "width": 144,
      "height": 144,
      "source": "6537bad40b|v1|webp q90 a100 h144"
    }
  },
  "videos": {
    "assets/video/fp-cap.mp4": {
      "poster": "/assets/media/video/fp-cap-poster.6b9c62657e.webp",
      "h264_720": "/assets/media/video/fp-cap-720.84d3d0a1fc.mp4",
      "h264_480": "/assets/media/video/fp-cap-480.11ae67d521.mp4",
      "av1_720": "/assets/media/video/fp-cap-av1-720.8f5c9c985a.mp4",
      "av1_480": "/assets/media/video/fp-cap-av1-480.525d358d13.mp4",
      "source": "84d3d0a1fc+140cadbcf1|v2|av1 svt p6 crf48/50|h264 crf30 slow 480|copy 720|poster webp q72 960"
    },
    "assets/video/fp-costaff.mp4": {
      "poster": "/assets/media/video/fp-costaff-poster.0876a71646.webp",
      "h264_720": "/assets/media/video/fp-costaff-720.f935c1b2c8.mp4",
      "h264_480": "/assets/media/video/fp-costaff-480.81c3a53ff5.mp4",
      "av1_720": "/assets/media/video/fp-costaff-av1-720.debbbd0890.mp4",
      "av1_480": "/assets/media/video/fp-costaff-av1-480.449f53b34a.mp4",
      "source": "f935c1b2c8+df538bf87d|v2|av1 svt p6 crf48/50|h264 crf30 slow 480|copy 720|poster webp q72 960"
    },
    "assets/video/fp-fraud.mp4": {
      "poster": "/assets/media/video/fp-fraud-poster.3322f3bd69.webp",
      "h264_720": "/assets/media/video/fp-fraud-720.494ce2c7f2.mp4",
      "h264_480": "/assets/media/video/fp-fraud-480.5691631a21.mp4",
      "av1_720": "/assets/media/video/fp-fraud-av1-720.1666ebfed9.mp4",
      "av1_480": "/assets/media/video/fp-fraud-av1-480.f6d48b572e.mp4",
      "source": "494ce2c7f2+0d753f2b68|v2|av1 svt p6 crf48/50|h264 crf30 slow 480|copy 720|poster webp q72 960"
    },
    "assets/video/fp-gta.mp4": {
      "poster": "/assets/media/video/fp-gta-poster.723cc69dd3.webp",
      "h264_720": "/assets/media/video/fp-gta-720.9832320573.mp4",
      "h264_480": "/assets/media/video/fp-gta-480.11727a74c4.mp4",
      "av1_720": "/assets/media/video/fp-gta-av1-720.8b666b6ea4.mp4",
      "av1_480": "/assets/media/video/fp-gta-av1-480.72caaab781.mp4",
      "source": "9832320573+940130d4b6|v2|av1 svt p6 crf48/50|h264 crf30 slow 480|copy 720|poster webp q72 960"
    },
    "assets/video/fp-nxp.mp4": {
      "poster": "/assets/media/video/fp-nxp-poster.0d3417df49.webp",
      "h264_720": "/assets/media/video/fp-nxp-720.be5a4a87f3.mp4",
      "h264_480": "/assets/media/video/fp-nxp-480.aa9a2acd40.mp4",
      "av1_720": "/assets/media/video/fp-nxp-av1-720.3b74f107cd.mp4",
      "av1_480": "/assets/media/video/fp-nxp-av1-480.ca22832064.mp4",
      "source": "42dbe8edad+e49fc85434|v2|av1 svt p6 crf48/50|h264 crf30 slow 480|copy 720|poster webp q72 960"
    },
    "assets/video/fp-tiger.mp4": {
      "poster": "/assets/media/video/fp-tiger-poster.ea01fcda8e.webp",
      "h264_720": "/assets/media/video/fp-tiger-720.086f327e80.mp4",
      "h264_480": "/assets/media/video/fp-tiger-480.db3400c273.mp4",
      "av1_720": "/assets/media/video/fp-tiger-av1-720.a2be52e1d5.mp4",
      "av1_480": "/assets/media/video/fp-tiger-av1-480.4565c5e3d5.mp4",
      "source": "086f327e80+0e53e7f17c|v2|av1 svt p6 crf48/50|h264 crf30 slow 480|copy 720|poster webp q72 960"
    },
    "assets/video/fp-xpath.mp4": {
      "poster": "/assets/media/video/fp-xpath-poster.c32a63eb84.webp",
      "h264_720": "/assets/media/video/fp-xpath-720.df429e3f1a.mp4",
      "h264_480": "/assets/media/video/fp-xpath-480.5bad4e8df4.mp4",
      "av1_720": "/assets/media/video/fp-xpath-av1-720.b265dc8dfc.mp4",
      "av1_480": "/assets/media/video/fp-xpath-av1-480.cd9d88aff9.mp4",
      "source": "df429e3f1a+460ad82524|v2|av1 svt p6 crf48/50|h264 crf30 slow 480|copy 720|poster webp q72 960"
    }
  }
};
