// AUTO-GENERATED by scripts/optimize-media.mjs — do not edit by hand.
// Re-run `npm run optimize:media` after adding or replacing any image, logo or video.
import type { MediaManifest } from './media.types';

export const MEDIA_MANIFEST: MediaManifest = {
  "images": {
    "assets/img/assessment/fat-beehive/fat-beehive1.jpeg": {
      "width": 3456,
      "height": 1994,
      "avif": "/assets/media/img/fat-beehive1-640.b3579925b4.avif 640w, /assets/media/img/fat-beehive1-1280.5f71bff9ff.avif 1280w, /assets/media/img/fat-beehive1-1920.46ff5e3e18.avif 1920w",
      "webp": "/assets/media/img/fat-beehive1-640.478506e761.webp 640w, /assets/media/img/fat-beehive1-1280.9f6df72b8b.webp 1280w, /assets/media/img/fat-beehive1-1920.0bb1cb4fbd.webp 1920w",
      "fallback": "/assets/media/img/fat-beehive1-1280.845b2a2144.jpg",
      "source": "82bd0a05ab|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/assessment/logic-bank/logic1.jpeg": {
      "width": 1280,
      "height": 740,
      "avif": "/assets/media/img/logic1-640.88871cff22.avif 640w, /assets/media/img/logic1-1280.b24e16deb0.avif 1280w",
      "webp": "/assets/media/img/logic1-640.ff17c3a2ab.webp 640w, /assets/media/img/logic1-1280.0f9b434a55.webp 1280w",
      "fallback": "/assets/media/img/logic1-1280.7f43f4552e.jpg",
      "source": "de7382d10a|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/assessment/logic-bank/logic2.jpeg": {
      "width": 3456,
      "height": 1996,
      "avif": "/assets/media/img/logic2-640.c03a3e1b56.avif 640w, /assets/media/img/logic2-1280.c8a6976a31.avif 1280w, /assets/media/img/logic2-1920.d1363534d2.avif 1920w",
      "webp": "/assets/media/img/logic2-640.efef5abed7.webp 640w, /assets/media/img/logic2-1280.6d8a3ea697.webp 1280w, /assets/media/img/logic2-1920.f27ebd3656.webp 1920w",
      "fallback": "/assets/media/img/logic2-1280.7cafbd8f61.jpg",
      "source": "0c0d26f4fa|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/assessment/logic-bank/logic3.jpeg": {
      "width": 3456,
      "height": 1996,
      "avif": "/assets/media/img/logic3-640.a5056a6b83.avif 640w, /assets/media/img/logic3-1280.52d99cfb3f.avif 1280w, /assets/media/img/logic3-1920.c54feb7729.avif 1920w",
      "webp": "/assets/media/img/logic3-640.468716248a.webp 640w, /assets/media/img/logic3-1280.d38b2cf133.webp 1280w, /assets/media/img/logic3-1920.d856832918.webp 1920w",
      "fallback": "/assets/media/img/logic3-1280.8c041e79d9.jpg",
      "source": "9484f47d6d|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/assessment/logic-bank/logic4.jpeg": {
      "width": 3456,
      "height": 1996,
      "avif": "/assets/media/img/logic4-640.b0495cf322.avif 640w, /assets/media/img/logic4-1280.6ae45d3297.avif 1280w, /assets/media/img/logic4-1920.0bf53b453a.avif 1920w",
      "webp": "/assets/media/img/logic4-640.4a6378ff53.webp 640w, /assets/media/img/logic4-1280.53fdeb304a.webp 1280w, /assets/media/img/logic4-1920.cc12df8774.webp 1920w",
      "fallback": "/assets/media/img/logic4-1280.c3526643be.jpg",
      "source": "dfe3f188c8|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/assessment/logic-bank/logic5.jpeg": {
      "width": 3456,
      "height": 2000,
      "avif": "/assets/media/img/logic5-640.ea4ea98f1f.avif 640w, /assets/media/img/logic5-1280.eb2ce45fc4.avif 1280w, /assets/media/img/logic5-1920.95764dc6b6.avif 1920w",
      "webp": "/assets/media/img/logic5-640.d09bfaeb23.webp 640w, /assets/media/img/logic5-1280.43e23db0c5.webp 1280w, /assets/media/img/logic5-1920.651827af29.webp 1920w",
      "fallback": "/assets/media/img/logic5-1280.8e3a7bd2cc.jpg",
      "source": "e1b5dfd38b|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/assessment/naologic/naologic1.jpeg": {
      "width": 3456,
      "height": 1998,
      "avif": "/assets/media/img/naologic1-640.9b88d642a3.avif 640w, /assets/media/img/naologic1-1280.f2e37694a4.avif 1280w, /assets/media/img/naologic1-1920.fde88e5ed7.avif 1920w",
      "webp": "/assets/media/img/naologic1-640.5a45426e4a.webp 640w, /assets/media/img/naologic1-1280.a19a2ee995.webp 1280w, /assets/media/img/naologic1-1920.ba8633b724.webp 1920w",
      "fallback": "/assets/media/img/naologic1-1280.37d366c25d.jpg",
      "source": "114d18c0f0|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/assessment/naologic/naologic2.jpeg": {
      "width": 3456,
      "height": 1994,
      "avif": "/assets/media/img/naologic2-640.80f4f3f8b0.avif 640w, /assets/media/img/naologic2-1280.3fabb5b34b.avif 1280w, /assets/media/img/naologic2-1920.cf70dfb3a3.avif 1920w",
      "webp": "/assets/media/img/naologic2-640.fb7a09eecc.webp 640w, /assets/media/img/naologic2-1280.28824a7d78.webp 1280w, /assets/media/img/naologic2-1920.92e70ce2a7.webp 1920w",
      "fallback": "/assets/media/img/naologic2-1280.0e0275be36.jpg",
      "source": "5aa0a77be9|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/cap-dashboard.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/cap-dashboard-640.0e23f7344b.avif 640w, /assets/media/img/cap-dashboard-1280.02af562fe1.avif 1280w, /assets/media/img/cap-dashboard-1920.e871f3e8d5.avif 1920w",
      "webp": "/assets/media/img/cap-dashboard-640.91093da824.webp 640w, /assets/media/img/cap-dashboard-1280.621e628542.webp 1280w, /assets/media/img/cap-dashboard-1920.451869081f.webp 1920w",
      "fallback": "/assets/media/img/cap-dashboard-1280.c7ae59cdf8.jpg",
      "source": "b41af02065|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/cap-disbursements.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/cap-disbursements-640.13b850e717.avif 640w, /assets/media/img/cap-disbursements-1280.049fdb1afb.avif 1280w, /assets/media/img/cap-disbursements-1920.7e4bc5b839.avif 1920w",
      "webp": "/assets/media/img/cap-disbursements-640.9dece8a019.webp 640w, /assets/media/img/cap-disbursements-1280.d5ce18ed13.webp 1280w, /assets/media/img/cap-disbursements-1920.def561a8e6.webp 1920w",
      "fallback": "/assets/media/img/cap-disbursements-1280.d1d5415397.jpg",
      "source": "42b252490c|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/cap-facility-requests.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/cap-facility-requests-640.b1ffa5a390.avif 640w, /assets/media/img/cap-facility-requests-1280.296b049b18.avif 1280w, /assets/media/img/cap-facility-requests-1920.21cb835bd3.avif 1920w",
      "webp": "/assets/media/img/cap-facility-requests-640.cbb267f462.webp 640w, /assets/media/img/cap-facility-requests-1280.4065fa4453.webp 1280w, /assets/media/img/cap-facility-requests-1920.c1e1c58cdc.webp 1920w",
      "fallback": "/assets/media/img/cap-facility-requests-1280.fd59c4c77a.jpg",
      "source": "a15029d8c1|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/cap-login.jpeg": {
      "width": 3422,
      "height": 1994,
      "avif": "/assets/media/img/cap-login-640.73864ccaf3.avif 640w, /assets/media/img/cap-login-1280.3b74ddb170.avif 1280w, /assets/media/img/cap-login-1920.7279dee764.avif 1920w",
      "webp": "/assets/media/img/cap-login-640.f386393415.webp 640w, /assets/media/img/cap-login-1280.194d3251b4.webp 1280w, /assets/media/img/cap-login-1920.48455ddedd.webp 1920w",
      "fallback": "/assets/media/img/cap-login-1280.49563b389a.jpg",
      "source": "0731edb239|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/costaff-calendar.avif": {
      "width": 1884,
      "height": 1176,
      "avif": "/assets/media/img/costaff-calendar-640.695c50a502.avif 640w, /assets/media/img/costaff-calendar-1280.0318717883.avif 1280w, /assets/media/img/costaff-calendar-1884.09f272ab85.avif 1884w",
      "webp": "/assets/media/img/costaff-calendar-640.203823a4da.webp 640w, /assets/media/img/costaff-calendar-1280.821f3b85b5.webp 1280w, /assets/media/img/costaff-calendar-1884.c4f4104382.webp 1884w",
      "fallback": "/assets/media/img/costaff-calendar-1280.996e21ef8c.jpg",
      "source": "0c03d1c3ae|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/costaff-home.jpeg": {
      "width": 1280,
      "height": 741,
      "avif": "/assets/media/img/costaff-home-640.41c4a9b409.avif 640w, /assets/media/img/costaff-home-1280.554c73c31e.avif 1280w",
      "webp": "/assets/media/img/costaff-home-640.77c8f1be36.webp 640w, /assets/media/img/costaff-home-1280.0ace1182d0.webp 1280w",
      "fallback": "/assets/media/img/costaff-home-1280.a142712496.jpg",
      "source": "c8d8ce028b|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/domestic-dashboard.png": {
      "width": 2180,
      "height": 1246,
      "avif": "/assets/media/img/domestic-dashboard-640.f26e12d690.avif 640w, /assets/media/img/domestic-dashboard-1280.4038f084cf.avif 1280w, /assets/media/img/domestic-dashboard-1920.68249b63ed.avif 1920w",
      "webp": "/assets/media/img/domestic-dashboard-640.66e684c7aa.webp 640w, /assets/media/img/domestic-dashboard-1280.7e33176dac.webp 1280w, /assets/media/img/domestic-dashboard-1920.0e70c890a2.webp 1920w",
      "fallback": "/assets/media/img/domestic-dashboard-1280.b09fb0ae04.jpg",
      "source": "693583e6d1|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/domestic-login.png": {
      "width": 1306,
      "height": 770,
      "avif": "/assets/media/img/domestic-login-640.7efa30a883.avif 640w, /assets/media/img/domestic-login-1280.1557b1286b.avif 1280w, /assets/media/img/domestic-login-1306.cfef8fb568.avif 1306w",
      "webp": "/assets/media/img/domestic-login-640.1c9bf2f3f0.webp 640w, /assets/media/img/domestic-login-1280.5d28cf370f.webp 1280w, /assets/media/img/domestic-login-1306.5cbb759e21.webp 1306w",
      "fallback": "/assets/media/img/domestic-login-1280.e43205d627.jpg",
      "source": "48fc3145b6|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/fraud-dashboard-dark.png": {
      "width": 1830,
      "height": 900,
      "avif": "/assets/media/img/fraud-dashboard-dark-640.04b880f818.avif 640w, /assets/media/img/fraud-dashboard-dark-1280.a73593fb76.avif 1280w, /assets/media/img/fraud-dashboard-dark-1830.5cf7b6250c.avif 1830w",
      "webp": "/assets/media/img/fraud-dashboard-dark-640.c5c6788278.webp 640w, /assets/media/img/fraud-dashboard-dark-1280.99add2562a.webp 1280w, /assets/media/img/fraud-dashboard-dark-1830.6c0e490d59.webp 1830w",
      "fallback": "/assets/media/img/fraud-dashboard-dark-1280.4897830675.jpg",
      "source": "a132349412|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/fraud-details-dark.png": {
      "width": 1118,
      "height": 762,
      "avif": "/assets/media/img/fraud-details-dark-640.a3e99dba3b.avif 640w, /assets/media/img/fraud-details-dark-1118.5982da4358.avif 1118w",
      "webp": "/assets/media/img/fraud-details-dark-640.1b570831fa.webp 640w, /assets/media/img/fraud-details-dark-1118.9112235db6.webp 1118w",
      "fallback": "/assets/media/img/fraud-details-dark-1118.78e08be10a.jpg",
      "source": "bc1df2d12e|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/nxp-applications.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/nxp-applications-640.9fb61f2a69.avif 640w, /assets/media/img/nxp-applications-1280.d830e21594.avif 1280w, /assets/media/img/nxp-applications-1920.7ba9a30fa4.avif 1920w",
      "webp": "/assets/media/img/nxp-applications-640.5fdd805b3f.webp 640w, /assets/media/img/nxp-applications-1280.3ca2c6214e.webp 1280w, /assets/media/img/nxp-applications-1920.f68753a75b.webp 1920w",
      "fallback": "/assets/media/img/nxp-applications-1280.a2bdde860e.jpg",
      "source": "aa779c0b05|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/nxp-cancelation.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/nxp-cancelation-640.fa6ca00706.avif 640w, /assets/media/img/nxp-cancelation-1280.014d6d3f97.avif 1280w, /assets/media/img/nxp-cancelation-1920.7f9101d76b.avif 1920w",
      "webp": "/assets/media/img/nxp-cancelation-640.194a3d2c54.webp 640w, /assets/media/img/nxp-cancelation-1280.c5779357bc.webp 1280w, /assets/media/img/nxp-cancelation-1920.fd8d40c33b.webp 1920w",
      "fallback": "/assets/media/img/nxp-cancelation-1280.d9d999d869.jpg",
      "source": "4e38fb45ad|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/nxp-ness.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/nxp-ness-640.3ad5b1808e.avif 640w, /assets/media/img/nxp-ness-1280.9724c1d721.avif 1280w, /assets/media/img/nxp-ness-1920.14efdc3bbf.avif 1920w",
      "webp": "/assets/media/img/nxp-ness-640.323f86c4a0.webp 640w, /assets/media/img/nxp-ness-1280.eb87a8eb87.webp 1280w, /assets/media/img/nxp-ness-1920.9ffa0c040d.webp 1920w",
      "fallback": "/assets/media/img/nxp-ness-1280.ef12f37038.jpg",
      "source": "f23c0aeee0|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/nxp-overview.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/nxp-overview-640.ce9318fe8e.avif 640w, /assets/media/img/nxp-overview-1280.87c076674d.avif 1280w, /assets/media/img/nxp-overview-1920.c5301de9f5.avif 1920w",
      "webp": "/assets/media/img/nxp-overview-640.c043d212f9.webp 640w, /assets/media/img/nxp-overview-1280.efad304173.webp 1280w, /assets/media/img/nxp-overview-1920.d356653371.webp 1920w",
      "fallback": "/assets/media/img/nxp-overview-1280.8b66e035b4.jpg",
      "source": "9a7d55d0ff|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/nxp-repatriation.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/nxp-repatriation-640.105fc80543.avif 640w, /assets/media/img/nxp-repatriation-1280.fbe2612099.avif 1280w, /assets/media/img/nxp-repatriation-1920.7d774e2450.avif 1920w",
      "webp": "/assets/media/img/nxp-repatriation-640.d9537c325f.webp 640w, /assets/media/img/nxp-repatriation-1280.7808b9d3ba.webp 1280w, /assets/media/img/nxp-repatriation-1920.9b1b41dc43.webp 1920w",
      "fallback": "/assets/media/img/nxp-repatriation-1280.b2af308787.jpg",
      "source": "d64cd01aa4|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/trade-dashboard.png": {
      "width": 2956,
      "height": 1662,
      "avif": "/assets/media/img/trade-dashboard-640.72e2c91467.avif 640w, /assets/media/img/trade-dashboard-1280.72e3cfc2ef.avif 1280w, /assets/media/img/trade-dashboard-1920.ef7ab8f343.avif 1920w",
      "webp": "/assets/media/img/trade-dashboard-640.6a1055db67.webp 640w, /assets/media/img/trade-dashboard-1280.febd2ed41e.webp 1280w, /assets/media/img/trade-dashboard-1920.3575430b2a.webp 1920w",
      "fallback": "/assets/media/img/trade-dashboard-1280.f22fc781b6.jpg",
      "source": "926b23374c|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/trade-settings.png": {
      "width": 2960,
      "height": 1664,
      "avif": "/assets/media/img/trade-settings-640.8610abb6ed.avif 640w, /assets/media/img/trade-settings-1280.3dc7cc0749.avif 1280w, /assets/media/img/trade-settings-1920.d7f049f628.avif 1920w",
      "webp": "/assets/media/img/trade-settings-640.7f488dd7bc.webp 640w, /assets/media/img/trade-settings-1280.6ed412a8c7.webp 1280w, /assets/media/img/trade-settings-1920.e221e038e2.webp 1920w",
      "fallback": "/assets/media/img/trade-settings-1280.e9bcc0371f.jpg",
      "source": "34ee00cfa0|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/xpath-charges.png": {
      "width": 1268,
      "height": 626,
      "avif": "/assets/media/img/xpath-charges-640.d0ad262c58.avif 640w, /assets/media/img/xpath-charges-1268.8685fd909e.avif 1268w",
      "webp": "/assets/media/img/xpath-charges-640.b78120d94e.webp 640w, /assets/media/img/xpath-charges-1268.0bf7d6ecf0.webp 1268w",
      "fallback": "/assets/media/img/xpath-charges-1268.ab7afdab56.jpg",
      "source": "a71ffffc77|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    },
    "assets/img/xpath-config.png": {
      "width": 1184,
      "height": 946,
      "avif": "/assets/media/img/xpath-config-640.04d4e16046.avif 640w, /assets/media/img/xpath-config-1184.6a4c1130c2.avif 1184w",
      "webp": "/assets/media/img/xpath-config-640.9aa17c824d.webp 640w, /assets/media/img/xpath-config-1184.c2dfbb656c.webp 1184w",
      "fallback": "/assets/media/img/xpath-config-1184.4f12118a19.jpg",
      "source": "d39a3ed7d7|v1|avif q60 e6 444|webp q80 e6 smart|jpeg mozjpeg q80"
    }
  },
  "logos": {
    "assets/logos/conclase.svg": {
      "src": "/assets/media/logos/conclase.144f6b1674.webp",
      "width": 334,
      "height": 144,
      "source": "cbc0c8af82|v1|webp q90 a100 h144"
    },
    "assets/logos/golden-scepter.svg": {
      "src": "/assets/media/logos/golden-scepter.a9dd805dc0.webp",
      "width": 365,
      "height": 144,
      "source": "3be337cffc|v1|webp q90 a100 h144"
    },
    "assets/logos/jumbo.svg": {
      "src": "/assets/media/logos/jumbo.ad1eb4180d.webp",
      "width": 144,
      "height": 144,
      "source": "3f735e57db|v1|webp q90 a100 h144"
    },
    "assets/logos/upperlink.svg": {
      "src": "/assets/media/logos/upperlink.983586f278.webp",
      "width": 144,
      "height": 144,
      "source": "6537bad40b|v1|webp q90 a100 h144"
    }
  },
  "videos": {
    "assets/video/fp-cap.mp4": {
      "poster": "/assets/media/video/fp-cap-poster.6b9c62657e.webp",
      "h264_720": "/assets/media/video/fp-cap-720.84d3d0a1fc.mp4",
      "h264_480": "/assets/media/video/fp-cap-480.11ae67d521.mp4",
      "av1_720": "/assets/media/video/fp-cap-av1-720.8f5c9c985a.mp4",
      "av1_480": "/assets/media/video/fp-cap-av1-480.525d358d13.mp4",
      "source": "84d3d0a1fc+140cadbcf1|v2|av1 svt p6 crf48/50|h264 crf30 slow 480|copy 720|poster webp q72 960"
    },
    "assets/video/fp-costaff.mp4": {
      "poster": "/assets/media/video/fp-costaff-poster.0876a71646.webp",
      "h264_720": "/assets/media/video/fp-costaff-720.f935c1b2c8.mp4",
      "h264_480": "/assets/media/video/fp-costaff-480.81c3a53ff5.mp4",
      "av1_720": "/assets/media/video/fp-costaff-av1-720.debbbd0890.mp4",
      "av1_480": "/assets/media/video/fp-costaff-av1-480.449f53b34a.mp4",
      "source": "f935c1b2c8+df538bf87d|v2|av1 svt p6 crf48/50|h264 crf30 slow 480|copy 720|poster webp q72 960"
    },
    "assets/video/fp-fraud.mp4": {
      "poster": "/assets/media/video/fp-fraud-poster.3322f3bd69.webp",
      "h264_720": "/assets/media/video/fp-fraud-720.494ce2c7f2.mp4",
      "h264_480": "/assets/media/video/fp-fraud-480.5691631a21.mp4",
      "av1_720": "/assets/media/video/fp-fraud-av1-720.1666ebfed9.mp4",
      "av1_480": "/assets/media/video/fp-fraud-av1-480.f6d48b572e.mp4",
      "source": "494ce2c7f2+0d753f2b68|v2|av1 svt p6 crf48/50|h264 crf30 slow 480|copy 720|poster webp q72 960"
    },
    "assets/video/fp-gta.mp4": {
      "poster": "/assets/media/video/fp-gta-poster.723cc69dd3.webp",
      "h264_720": "/assets/media/video/fp-gta-720.9832320573.mp4",
      "h264_480": "/assets/media/video/fp-gta-480.11727a74c4.mp4",
      "av1_720": "/assets/media/video/fp-gta-av1-720.8b666b6ea4.mp4",
      "av1_480": "/assets/media/video/fp-gta-av1-480.72caaab781.mp4",
      "source": "9832320573+940130d4b6|v2|av1 svt p6 crf48/50|h264 crf30 slow 480|copy 720|poster webp q72 960"
    },
    "assets/video/fp-nxp.mp4": {
      "poster": "/assets/media/video/fp-nxp-poster.0d3417df49.webp",
      "h264_720": "/assets/media/video/fp-nxp-720.be5a4a87f3.mp4",
      "h264_480": "/assets/media/video/fp-nxp-480.aa9a2acd40.mp4",
      "av1_720": "/assets/media/video/fp-nxp-av1-720.3b74f107cd.mp4",
      "av1_480": "/assets/media/video/fp-nxp-av1-480.ca22832064.mp4",
      "source": "42dbe8edad+e49fc85434|v2|av1 svt p6 crf48/50|h264 crf30 slow 480|copy 720|poster webp q72 960"
    },
    "assets/video/fp-tiger.mp4": {
      "poster": "/assets/media/video/fp-tiger-poster.ea01fcda8e.webp",
      "h264_720": "/assets/media/video/fp-tiger-720.086f327e80.mp4",
      "h264_480": "/assets/media/video/fp-tiger-480.db3400c273.mp4",
      "av1_720": "/assets/media/video/fp-tiger-av1-720.a2be52e1d5.mp4",
      "av1_480": "/assets/media/video/fp-tiger-av1-480.4565c5e3d5.mp4",
      "source": "086f327e80+0e53e7f17c|v2|av1 svt p6 crf48/50|h264 crf30 slow 480|copy 720|poster webp q72 960"
    },
    "assets/video/fp-xpath.mp4": {
      "poster": "/assets/media/video/fp-xpath-poster.c32a63eb84.webp",
      "h264_720": "/assets/media/video/fp-xpath-720.df429e3f1a.mp4",
      "h264_480": "/assets/media/video/fp-xpath-480.5bad4e8df4.mp4",
      "av1_720": "/assets/media/video/fp-xpath-av1-720.b265dc8dfc.mp4",
      "av1_480": "/assets/media/video/fp-xpath-av1-480.cd9d88aff9.mp4",
      "source": "df429e3f1a+460ad82524|v2|av1 svt p6 crf48/50|h264 crf30 slow 480|copy 720|poster webp q72 960"
    }
  }
};
